name: onlyoffice-desktopeditors
version: "6.1.0"
summary: "An office suite that allowing to create, view and edit local documents."
description: "ONLYOFFICE Desktop Editors is a free office suite that combines text, spreadsheet and presentation editors allowing to create, view and edit documents stored on your Windows/Linux PC or Mac without an Internet connection. It is fully compatible with Office Open XML formats: .docx, .xlsx, .pptx."
grade: stable
confinement: strict
base: core18
icon: icons/asc-de-256.png
architectures:
  - amd64

apps:
  onlyoffice-desktopeditors:
    command: usr/bin/desktopeditors
    desktop: usr/share/applications/onlyoffice-desktopeditors.desktop
    plugs:
      - browser-support
      - cups-control
      - desktop
      - gsettings
      - home
      - locale-control
      - network
      - opengl
      - removable-media
      - unity7
      - x11
parts:
  onlyoffice-desktopeditors:
    plugin: dump
    source: http://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors_amd64.deb
    source-type: deb
    stage-packages:
      - on amd64:
        - fonts-crosextra-carlito
        - fonts-dejavu
        - fonts-liberation
        - fonts-opensymbol
        - fonts-takao-gothic
        - gsettings-desktop-schemas
        - gsettings-ubuntu-schemas
        - libasyncns0
        - libatk-adaptor
        - libc6
        - libcairo2
        - libcanberra-gtk-module
        - libcomerr2
        - libcurl3
        - libcurl3-gnutls
        - libflac8
        - libgail-3-0
        - libgcc1
        - libgconf-2-4
        - libgcrypt20
        - libgl1-mesa-dri
        - libgpg-error0
        - libgsettings-qt1
        - libgstreamer-plugins-base1.0-0
        - libgstreamer1.0-0
        - libgtkglext1
        - liblzma5
        - libnss3
        - liborc-0.4-0
        - libpcre3
        - libpulse0
        - libqt5qml5
        - libqt5quick5
        - libselinux1
        - libsndfile1
        - libstdc++6
        - libsystemd0
        - libuuid1
        - libvorbisenc2
        - libxcb-icccm4
        - libxcb-image0
        - libxcb-keysyms1
        - libxcb-randr0
        - libxcb-render-util0
        - libxcb-shape0
        - libxcb-util1
        - libxcb-xkb1
        - libxkbcommon-x11-0
        - libxml2
        - libxss1
        - locales-all
        - overlay-scrollbar-gtk2
        - packagekit-gtk3-module
        - ttf-mscorefonts-installer
        - unity-gtk2-module
        - x11-common
        - zlib1g
      - else fail
    override-build: |
      snapcraftctl build
      mv $SNAPCRAFT_PART_INSTALL/usr/bin/desktopeditors $SNAPCRAFT_PART_INSTALL/usr/bin/desktopeditors-old &&
      sed 's|=onlyoffice-desktopeditors|\=${SNAP}/opt/onlyoffice/desktopeditors/asc-de-256.png|g' -i $SNAPCRAFT_PART_INSTALL/usr/share/applications/onlyoffice-desktopeditors.desktop

#    install: |
#      mv $SNAPCRAFT_PART_INSTALL/opt/onlyoffice/desktopeditors/converter/x2t $SNAPCRAFT_PART_INSTALL/opt/onlyoffice/desktopeditors/converter/x2t.bin

#  mscore-fonts:
#    plugin: dump
#    source: https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
#    source-type: rpm

  starter:
    plugin: dump
    source: ./bin/
    organize:
      run-desktopeditors.sh: usr/bin/desktopeditors
#      x2t.sh: $SNAPCRAFT_PART_INSTALL/opt/onlyoffice/desktopeditors/converter/x2t
